"""rename table

Revision ID: 81e2b7d61b3c
Revises: e031e17aa9ad
Create Date: 2024-12-20 13:52:01.471750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e2b7d61b3c'
down_revision: Union[str, None] = 'e031e17aa9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_time', sa.DateTime(), nullable=True))
    op.drop_column('appointments', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'appointment_time')
    # ### end Alembic commands ###
